version: '3.8'

services:
  frontend:
    image: node:18
    container_name: todo_frontend
    build:
      context: .
      dockerfile: ./app/frontend/Dockerfile
    working_dir: /app/frontend
    volumes:
      - ./app/frontend:/app/frontend
    ports:
      - "3000:3000"
    stdin_open: true
    command: npm start
