version: '3.8'

services:
  frontend:
    image: node:18
    container_name: todo_frontend
    build:
      context: .
      dockerfile: ./app/frontend/Dockerfile
    working_dir: /app/frontend
    volumes:
      - ./app/frontend:/app/frontend
    ports:
      - "3000:3000"
    stdin_open: true
    command: npm start
  backend:
    image: golang:1.18-alpine
    container_name: todo_backend
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    working_dir: /app/backend
    volumes:
      - ./app/backend:/app/backend
    ports:
      - "8080:8080"
    stdin_open: true
    command: ["go", "run", "main.go"]
